In [6]:
import numpy as np

## Arrays and Vectorization

**Arrays** are sequences of same-type data points (most-often numbers).  Numpy allows us to work with the sequence without writing a for-loop, using a technique called **vectorization**.  

Besides an **array()** class, Numpy also includes a lot of math functions, which makes analysis much easier.  Let's try some out!

## Numpy Exercises

### Building Arrays

Numpy has some convenient array-building functions as well.  Some commonly-used are examples are **arange()**, **linspace()**, **zeros()**, and the random number generation functions in **random**.

| function | Purpose |  Example |
| :-----------: | :-------------: | :-------------: |
| **np.arange()**                  | Makes an array with all the integers between two values | np.arange(2, 7) |
| **np.linspace()**               | Makes a specific-length array |  np.linspace(2, 3, 10) |
| **np.zeros()**                    | Makes an array of all zeros | np.zeros(5) |
| **np.ones()**                     | Makes an array of all ones | np.ones(3) |
| **np.random.random()** | Makes an array of random numbers | np.random.random(100) |
| **np.random.randn()**     | Makes an array of normally-distributed random numbers | np.random.randn(100) |


1. Make an array containing the numbers 1 to 15.

In [7]:
np.arange(1, 16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

2. Make an array containing 20 zeros.

In [8]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

3. Make an array contain 20 ones!

In [9]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

4. Generate an array of 10 random numbers from Numpy's **random** submodule, using any function you want.

In [17]:
np.random.randint(1, 10, 10)

array([8, 4, 7, 7, 5, 2, 7, 8, 9, 2])

In [19]:
np.arange(1, 10, step = 5)

array([1, 6])

In [20]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [18]:
np.random.seed(42) # set seed to repeat
np.random.random(10)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [14]:
np.random.random(10)

array([0.21741639, 0.08930503, 0.40141319, 0.35598578, 0.41893934,
       0.23097354, 0.40016929, 0.78238257, 0.79619981, 0.24631487])

## Statistics Methods on Arrays

Arrays have many useful math methods.  For example, to get the mean of an array of numbers:

```python
data = np.random.random(100)
data.mean()
```

**Exercise**: Calculate the statistics on the following numbers:

In [23]:
data = np.arange(2, 7)
data

array([2, 3, 4, 5, 6])

1. Get the mean of the data.

2. What is the sum of the data?

3. The maximum of the data?

4. The standard deviation of the data?

In [24]:
from scipy import stats
stats.sem(data)

0.7071067811865476

## Statistics Functions on Arrays

Numpy also has many useful statistics **functions**.  These take an array as an input and can be found inside the **np** library.  Sometimes, the same functionality can be found both as a Numpy function  and an array method, giving you the choice of how you'd like to use it.  


For example, the following **method**:


```python
data = np.random.random(100)
data.mean()
```

can also be used as a **function**:


```python
data = np.random.random(100)
np.mean(data)
```

**Exercise**: Calculate the statistics on the following numbers, this time using the **function** version of the previous methods.

In [ ]:
data = np.arange(2, 7)
data

array([2, 3, 4, 5, 6])

1. Get the mean of the data.

2. What is the sum of the data?

In [25]:
sum(data)

20

In [26]:
np.sum(data)

20

In [27]:
data.sum()

20

3. What is the minimum of the data?

4. The standard deviation?

## Arithmetic with Arrays

Arrays can also be added, subtracted, multiplied, and divided.  

For example, to add 10 to all values in an array:

```python
data = np.random.randn(5)
print(data)
print(data + 10)
```

Here is multiplying two arrays together: 

```python
print(data )
print(data * data)
```



**Exercises**: Modify the following arrays using the math operators  (+, -, *, /)

In [7]:
data = np.arange(-3, 5)
data

array([-3, -2, -1,  0,  1,  2,  3,  4])

1. Multiply the data by 100

2. Add 40 to each value in the array.

3. Divide the numbers by 100

4. Subtract the data from itself.

## Extra Exercises

### Exercise: Other math functions

1. Calculate the square of all the numbers from 0 to 8.

2. Calculate the square roots of all the numbers from 0 to 8.

3. Make an array of 20 values, all of them 2's.

In [30]:
np.repeat(np.arange(6), 2, axis = 0)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [29]:
np.repeat(np.arange(6), 2, axis = 0).T.flatten()

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

4. Subtract the mean of the array from each element in the array (a.k.a. "mean-centering" the values)

In [36]:
data = np.random.randn(20)
data

array([-0.6006, -0.2917, -0.6017,  1.8523, -0.0135, -1.0577,  0.8225,
       -1.2208,  0.2089, -1.9597, -1.3282,  0.1969,  0.7385,  0.1714,
       -0.1156, -0.3011, -1.4785, -0.7198, -0.4606,  1.0571])

In [37]:
data

array([-0.6006, -0.2917, -0.6017,  1.8523, -0.0135, -1.0577,  0.8225,
       -1.2208,  0.2089, -1.9597, -1.3282,  0.1969,  0.7385,  0.1714,
       -0.1156, -0.3011, -1.4785, -0.7198, -0.4606,  1.0571])

In [39]:
np.set_printoptions(precision = 2, suppress = True)

In [40]:
data

array([-0.6 , -0.29, -0.6 ,  1.85, -0.01, -1.06,  0.82, -1.22,  0.21,
       -1.96, -1.33,  0.2 ,  0.74,  0.17, -0.12, -0.3 , -1.48, -0.72,
       -0.46,  1.06])

### Translating Algorithms into Code

Calculate the standard deviation of an array's values, without using the numpy.std() function.  (Formula can be found here: http://www.mathsisfun.com/data/standard-deviation-formulas.html)

1. Work out the Mean (the simple average of the numbers)
2. Then for each number: subtract the Mean and square the result
3. Then work out the mean of those squared differences.
4. Take the square root of that and we are done!


In [48]:
data = np.random.randn(100)
data_mean = np.mean(data)
data_square = np.square(data - data_mean)
data_sum = np.sum(data_square)
data_sd = np.sqrt(data_sum / len(data))
data_sd

0.9514541564801084

In [49]:
# in one line
np.sqrt(np.sum((data - np.mean(data)) ** 2)/ len(data))

0.9514541564801084